apiVersion: v1
kind: Serice
metadata:
  name: ${name}-service-folder
spec:
  selector:
    app: ${name}-folder
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: ${name}-ingress-folder
   annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
   rules:
   - host: ${name}.example.com
     http:
       paths:
       - path: /
         backend:
            serviceName: ${name}-service-folder
            servicePort: 22
