apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}-folder
  namespace: default
  labels:
    app: ${name}-folder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${name}-folder
  template:
    metadata:
      labels:
        app: ${name}-folder
    spec:
      containers:
      - name: ${name}
        image: ${image}
        ports:
        - containerPort: 22
          name: workspace-ssh

